// <auto-generated />
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Infrastructure.Migrations;

[DbContext(typeof(ElectricityDbContext))]
partial class ElectricityDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Domain.Counter.HouseholdMeteringPlant", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("OBJ_GV_TIPAS")
                    .HasMaxLength(16)
                    .HasColumnType("nvarchar(16)");

                b.Property<int>("OBJ_NUMERIS")
                    .HasColumnType("int");

                b.Property<string>("OBT_PAVADINIMAS")
                    .HasMaxLength(32)
                    .HasColumnType("nvarchar(32)");

                b.Property<DateTime>("PL_T")
                    .HasColumnType("datetime2");

                b.Property<decimal?>("PMinus")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal?>("PPlus")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("TINKLAS")
                    .HasMaxLength(64)
                    .HasColumnType("nvarchar(64)");

                b.HasKey("Id");

                b.ToTable("HouseholdMeteringPlants");
            });
#pragma warning restore 612, 618
    }
}